# Generated by Django 6.0.6 on 2026-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
